//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JavaGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IJavaGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class JavaGrammarBaseListener : IJavaGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] JavaGrammarParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] JavaGrammarParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] JavaGrammarParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] JavaGrammarParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] JavaGrammarParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] JavaGrammarParser.CompilationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclaration([NotNull] JavaGrammarParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclaration([NotNull] JavaGrammarParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.importDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportDeclaration([NotNull] JavaGrammarParser.ImportDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.importDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportDeclaration([NotNull] JavaGrammarParser.ImportDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.qualifiedIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedIdentifier([NotNull] JavaGrammarParser.QualifiedIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.qualifiedIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedIdentifier([NotNull] JavaGrammarParser.QualifiedIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] JavaGrammarParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] JavaGrammarParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] JavaGrammarParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] JavaGrammarParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyClassBodyDeclaration([NotNull] JavaGrammarParser.EmptyClassBodyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyClassBodyDeclaration([NotNull] JavaGrammarParser.EmptyClassBodyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MemberClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberClassBodyDeclaration([NotNull] JavaGrammarParser.MemberClassBodyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MemberClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberClassBodyDeclaration([NotNull] JavaGrammarParser.MemberClassBodyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StaticBlockClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStaticBlockClassBodyDeclaration([NotNull] JavaGrammarParser.StaticBlockClassBodyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StaticBlockClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStaticBlockClassBodyDeclaration([NotNull] JavaGrammarParser.StaticBlockClassBodyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FieldOrMethodMember</c>
	/// labeled alternative in <see cref="JavaGrammarParser.memberDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOrMethodMember([NotNull] JavaGrammarParser.FieldOrMethodMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FieldOrMethodMember</c>
	/// labeled alternative in <see cref="JavaGrammarParser.memberDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOrMethodMember([NotNull] JavaGrammarParser.FieldOrMethodMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VoidMethodMember</c>
	/// labeled alternative in <see cref="JavaGrammarParser.memberDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVoidMethodMember([NotNull] JavaGrammarParser.VoidMethodMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VoidMethodMember</c>
	/// labeled alternative in <see cref="JavaGrammarParser.memberDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVoidMethodMember([NotNull] JavaGrammarParser.VoidMethodMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.methodOrFieldDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodOrFieldDecl([NotNull] JavaGrammarParser.MethodOrFieldDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.methodOrFieldDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodOrFieldDecl([NotNull] JavaGrammarParser.MethodOrFieldDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FieldRest</c>
	/// labeled alternative in <see cref="JavaGrammarParser.methodOrFieldRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldRest([NotNull] JavaGrammarParser.FieldRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FieldRest</c>
	/// labeled alternative in <see cref="JavaGrammarParser.methodOrFieldRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldRest([NotNull] JavaGrammarParser.FieldRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MethodRest</c>
	/// labeled alternative in <see cref="JavaGrammarParser.methodOrFieldRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodRest([NotNull] JavaGrammarParser.MethodRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MethodRest</c>
	/// labeled alternative in <see cref="JavaGrammarParser.methodOrFieldRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodRest([NotNull] JavaGrammarParser.MethodRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.fieldDeclaratorsRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDeclaratorsRest([NotNull] JavaGrammarParser.FieldDeclaratorsRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.fieldDeclaratorsRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDeclaratorsRest([NotNull] JavaGrammarParser.FieldDeclaratorsRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.methodDeclaratorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDeclaratorRest([NotNull] JavaGrammarParser.MethodDeclaratorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.methodDeclaratorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDeclaratorRest([NotNull] JavaGrammarParser.MethodDeclaratorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.voidMethodDeclaratorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVoidMethodDeclaratorRest([NotNull] JavaGrammarParser.VoidMethodDeclaratorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.voidMethodDeclaratorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVoidMethodDeclaratorRest([NotNull] JavaGrammarParser.VoidMethodDeclaratorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameters([NotNull] JavaGrammarParser.FormalParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameters([NotNull] JavaGrammarParser.FormalParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.formalParameterDecls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterDecls([NotNull] JavaGrammarParser.FormalParameterDeclsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.formalParameterDecls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterDecls([NotNull] JavaGrammarParser.FormalParameterDeclsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.formalParameterDeclsRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterDeclsRest([NotNull] JavaGrammarParser.FormalParameterDeclsRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.formalParameterDeclsRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterDeclsRest([NotNull] JavaGrammarParser.FormalParameterDeclsRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaratorId([NotNull] JavaGrammarParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaratorId([NotNull] JavaGrammarParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarator([NotNull] JavaGrammarParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarator([NotNull] JavaGrammarParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableDeclaratorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaratorRest([NotNull] JavaGrammarParser.VariableDeclaratorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableDeclaratorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaratorRest([NotNull] JavaGrammarParser.VariableDeclaratorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableDeclarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarators([NotNull] JavaGrammarParser.VariableDeclaratorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableDeclarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarators([NotNull] JavaGrammarParser.VariableDeclaratorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableInitializer([NotNull] JavaGrammarParser.VariableInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableInitializer([NotNull] JavaGrammarParser.VariableInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.arrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayInitializer([NotNull] JavaGrammarParser.ArrayInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.arrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayInitializer([NotNull] JavaGrammarParser.ArrayInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableInitializers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableInitializers([NotNull] JavaGrammarParser.VariableInitializersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableInitializers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableInitializers([NotNull] JavaGrammarParser.VariableInitializersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] JavaGrammarParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] JavaGrammarParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.blockStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStatements([NotNull] JavaGrammarParser.BlockStatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.blockStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStatements([NotNull] JavaGrammarParser.BlockStatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LocalVariableBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableBlockStatement([NotNull] JavaGrammarParser.LocalVariableBlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LocalVariableBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableBlockStatement([NotNull] JavaGrammarParser.LocalVariableBlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LabeledStatementBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabeledStatementBlockStatement([NotNull] JavaGrammarParser.LabeledStatementBlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LabeledStatementBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabeledStatementBlockStatement([NotNull] JavaGrammarParser.LabeledStatementBlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StatementBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementBlockStatement([NotNull] JavaGrammarParser.StatementBlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StatementBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementBlockStatement([NotNull] JavaGrammarParser.StatementBlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.localVariableDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclarationStatement([NotNull] JavaGrammarParser.LocalVariableDeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.localVariableDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclarationStatement([NotNull] JavaGrammarParser.LocalVariableDeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>InnerBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInnerBlockStatement([NotNull] JavaGrammarParser.InnerBlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InnerBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInnerBlockStatement([NotNull] JavaGrammarParser.InnerBlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyStatement([NotNull] JavaGrammarParser.EmptyStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyStatement([NotNull] JavaGrammarParser.EmptyStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LabeledStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabeledStatement([NotNull] JavaGrammarParser.LabeledStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LabeledStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabeledStatement([NotNull] JavaGrammarParser.LabeledStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IfStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] JavaGrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] JavaGrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SwitchStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatement([NotNull] JavaGrammarParser.SwitchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SwitchStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatement([NotNull] JavaGrammarParser.SwitchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>WhileStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] JavaGrammarParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>WhileStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] JavaGrammarParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoWhileStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoWhileStatement([NotNull] JavaGrammarParser.DoWhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoWhileStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoWhileStatement([NotNull] JavaGrammarParser.DoWhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ForStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] JavaGrammarParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] JavaGrammarParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BreakStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] JavaGrammarParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] JavaGrammarParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ContinueStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] JavaGrammarParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ContinueStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] JavaGrammarParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] JavaGrammarParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] JavaGrammarParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] JavaGrammarParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] JavaGrammarParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.statementExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementExpression([NotNull] JavaGrammarParser.StatementExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.statementExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementExpression([NotNull] JavaGrammarParser.StatementExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.switchBlockStatementGroups"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBlockStatementGroups([NotNull] JavaGrammarParser.SwitchBlockStatementGroupsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.switchBlockStatementGroups"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBlockStatementGroups([NotNull] JavaGrammarParser.SwitchBlockStatementGroupsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.switchBlockStatementGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBlockStatementGroup([NotNull] JavaGrammarParser.SwitchBlockStatementGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.switchBlockStatementGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBlockStatementGroup([NotNull] JavaGrammarParser.SwitchBlockStatementGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.switchLabels"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchLabels([NotNull] JavaGrammarParser.SwitchLabelsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.switchLabels"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchLabels([NotNull] JavaGrammarParser.SwitchLabelsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CaseExprLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseExprLabel([NotNull] JavaGrammarParser.CaseExprLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CaseExprLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseExprLabel([NotNull] JavaGrammarParser.CaseExprLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CaseEnumLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseEnumLabel([NotNull] JavaGrammarParser.CaseEnumLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CaseEnumLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseEnumLabel([NotNull] JavaGrammarParser.CaseEnumLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DefaultLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultLabel([NotNull] JavaGrammarParser.DefaultLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DefaultLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultLabel([NotNull] JavaGrammarParser.DefaultLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.enumConstantName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumConstantName([NotNull] JavaGrammarParser.EnumConstantNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.enumConstantName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumConstantName([NotNull] JavaGrammarParser.EnumConstantNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EnhancedForControl</c>
	/// labeled alternative in <see cref="JavaGrammarParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnhancedForControl([NotNull] JavaGrammarParser.EnhancedForControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EnhancedForControl</c>
	/// labeled alternative in <see cref="JavaGrammarParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnhancedForControl([NotNull] JavaGrammarParser.EnhancedForControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TraditionalForControl</c>
	/// labeled alternative in <see cref="JavaGrammarParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTraditionalForControl([NotNull] JavaGrammarParser.TraditionalForControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TraditionalForControl</c>
	/// labeled alternative in <see cref="JavaGrammarParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTraditionalForControl([NotNull] JavaGrammarParser.TraditionalForControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.forVarControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForVarControl([NotNull] JavaGrammarParser.ForVarControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.forVarControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForVarControl([NotNull] JavaGrammarParser.ForVarControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.forInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForInit([NotNull] JavaGrammarParser.ForInitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.forInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForInit([NotNull] JavaGrammarParser.ForInitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.forDeclarationContext"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForDeclarationContext([NotNull] JavaGrammarParser.ForDeclarationContextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.forDeclarationContext"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForDeclarationContext([NotNull] JavaGrammarParser.ForDeclarationContextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.forUpdate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForUpdate([NotNull] JavaGrammarParser.ForUpdateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.forUpdate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForUpdate([NotNull] JavaGrammarParser.ForUpdateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimaryExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpression([NotNull] JavaGrammarParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimaryExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpression([NotNull] JavaGrammarParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AssignmentExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] JavaGrammarParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignmentExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] JavaGrammarParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.assignmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentOperator([NotNull] JavaGrammarParser.AssignmentOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.assignmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentOperator([NotNull] JavaGrammarParser.AssignmentOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>InfixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInfixExpression([NotNull] JavaGrammarParser.InfixExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InfixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInfixExpression([NotNull] JavaGrammarParser.InfixExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SimpleExpression2</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleExpression2([NotNull] JavaGrammarParser.SimpleExpression2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SimpleExpression2</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleExpression2([NotNull] JavaGrammarParser.SimpleExpression2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.infixOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInfixOp([NotNull] JavaGrammarParser.InfixOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.infixOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInfixOp([NotNull] JavaGrammarParser.InfixOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrefixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixExpression([NotNull] JavaGrammarParser.PrefixExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrefixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixExpression([NotNull] JavaGrammarParser.PrefixExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCastExpression([NotNull] JavaGrammarParser.CastExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCastExpression([NotNull] JavaGrammarParser.CastExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PostfixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfixExpression([NotNull] JavaGrammarParser.PostfixExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PostfixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfixExpression([NotNull] JavaGrammarParser.PostfixExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.prefixOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixOp([NotNull] JavaGrammarParser.PrefixOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.prefixOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixOp([NotNull] JavaGrammarParser.PrefixOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.postfixOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfixOp([NotNull] JavaGrammarParser.PostfixOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.postfixOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfixOp([NotNull] JavaGrammarParser.PostfixOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralPrimary([NotNull] JavaGrammarParser.LiteralPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralPrimary([NotNull] JavaGrammarParser.LiteralPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenthesizedPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesizedPrimary([NotNull] JavaGrammarParser.ParenthesizedPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenthesizedPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesizedPrimary([NotNull] JavaGrammarParser.ParenthesizedPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IdentifierPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierPrimary([NotNull] JavaGrammarParser.IdentifierPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IdentifierPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierPrimary([NotNull] JavaGrammarParser.IdentifierPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NewCreatorPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewCreatorPrimary([NotNull] JavaGrammarParser.NewCreatorPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NewCreatorPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewCreatorPrimary([NotNull] JavaGrammarParser.NewCreatorPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.parExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParExpression([NotNull] JavaGrammarParser.ParExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.parExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParExpression([NotNull] JavaGrammarParser.ParExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ClassLiteralSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassLiteralSuffix([NotNull] JavaGrammarParser.ClassLiteralSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ClassLiteralSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassLiteralSuffix([NotNull] JavaGrammarParser.ClassLiteralSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccessSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccessSuffix([NotNull] JavaGrammarParser.ArrayAccessSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccessSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccessSuffix([NotNull] JavaGrammarParser.ArrayAccessSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArgumentsSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentsSuffix([NotNull] JavaGrammarParser.ArgumentsSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArgumentsSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentsSuffix([NotNull] JavaGrammarParser.ArgumentsSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] JavaGrammarParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] JavaGrammarParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] JavaGrammarParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] JavaGrammarParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MethodOrFieldSelector</c>
	/// labeled alternative in <see cref="JavaGrammarParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodOrFieldSelector([NotNull] JavaGrammarParser.MethodOrFieldSelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MethodOrFieldSelector</c>
	/// labeled alternative in <see cref="JavaGrammarParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodOrFieldSelector([NotNull] JavaGrammarParser.MethodOrFieldSelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArraySelector</c>
	/// labeled alternative in <see cref="JavaGrammarParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArraySelector([NotNull] JavaGrammarParser.ArraySelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArraySelector</c>
	/// labeled alternative in <see cref="JavaGrammarParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArraySelector([NotNull] JavaGrammarParser.ArraySelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BasicTypeType</c>
	/// labeled alternative in <see cref="JavaGrammarParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicTypeType([NotNull] JavaGrammarParser.BasicTypeTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BasicTypeType</c>
	/// labeled alternative in <see cref="JavaGrammarParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicTypeType([NotNull] JavaGrammarParser.BasicTypeTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ReferenceTypeType</c>
	/// labeled alternative in <see cref="JavaGrammarParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReferenceTypeType([NotNull] JavaGrammarParser.ReferenceTypeTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ReferenceTypeType</c>
	/// labeled alternative in <see cref="JavaGrammarParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReferenceTypeType([NotNull] JavaGrammarParser.ReferenceTypeTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.basicType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicType([NotNull] JavaGrammarParser.BasicTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.basicType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicType([NotNull] JavaGrammarParser.BasicTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.referenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReferenceType([NotNull] JavaGrammarParser.ReferenceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.referenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReferenceType([NotNull] JavaGrammarParser.ReferenceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArguments([NotNull] JavaGrammarParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArguments([NotNull] JavaGrammarParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.referenceTypeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReferenceTypeList([NotNull] JavaGrammarParser.ReferenceTypeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.referenceTypeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReferenceTypeList([NotNull] JavaGrammarParser.ReferenceTypeListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] JavaGrammarParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] JavaGrammarParser.ModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableModifier([NotNull] JavaGrammarParser.VariableModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableModifier([NotNull] JavaGrammarParser.VariableModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.typeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArgumentsOrDiamond([NotNull] JavaGrammarParser.TypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.typeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArgumentsOrDiamond([NotNull] JavaGrammarParser.TypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreator([NotNull] JavaGrammarParser.CreatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreator([NotNull] JavaGrammarParser.CreatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreatedName([NotNull] JavaGrammarParser.CreatedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreatedName([NotNull] JavaGrammarParser.CreatedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassCreatorRest([NotNull] JavaGrammarParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassCreatorRest([NotNull] JavaGrammarParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.arrayCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayCreatorRest([NotNull] JavaGrammarParser.ArrayCreatorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.arrayCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayCreatorRest([NotNull] JavaGrammarParser.ArrayCreatorRestContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
