//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JavaGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JavaGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IJavaGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] JavaGrammarParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] JavaGrammarParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] JavaGrammarParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] JavaGrammarParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilationUnit([NotNull] JavaGrammarParser.CompilationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilationUnit([NotNull] JavaGrammarParser.CompilationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclaration([NotNull] JavaGrammarParser.TypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclaration([NotNull] JavaGrammarParser.TypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportDeclaration([NotNull] JavaGrammarParser.ImportDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportDeclaration([NotNull] JavaGrammarParser.ImportDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.qualifiedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedIdentifier([NotNull] JavaGrammarParser.QualifiedIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.qualifiedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedIdentifier([NotNull] JavaGrammarParser.QualifiedIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] JavaGrammarParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] JavaGrammarParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] JavaGrammarParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] JavaGrammarParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyClassBodyDeclaration([NotNull] JavaGrammarParser.EmptyClassBodyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyClassBodyDeclaration([NotNull] JavaGrammarParser.EmptyClassBodyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MemberClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberClassBodyDeclaration([NotNull] JavaGrammarParser.MemberClassBodyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MemberClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberClassBodyDeclaration([NotNull] JavaGrammarParser.MemberClassBodyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StaticBlockClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticBlockClassBodyDeclaration([NotNull] JavaGrammarParser.StaticBlockClassBodyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StaticBlockClassBodyDeclaration</c>
	/// labeled alternative in <see cref="JavaGrammarParser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticBlockClassBodyDeclaration([NotNull] JavaGrammarParser.StaticBlockClassBodyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FieldOrMethodMember</c>
	/// labeled alternative in <see cref="JavaGrammarParser.memberDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldOrMethodMember([NotNull] JavaGrammarParser.FieldOrMethodMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FieldOrMethodMember</c>
	/// labeled alternative in <see cref="JavaGrammarParser.memberDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldOrMethodMember([NotNull] JavaGrammarParser.FieldOrMethodMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VoidMethodMember</c>
	/// labeled alternative in <see cref="JavaGrammarParser.memberDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVoidMethodMember([NotNull] JavaGrammarParser.VoidMethodMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VoidMethodMember</c>
	/// labeled alternative in <see cref="JavaGrammarParser.memberDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVoidMethodMember([NotNull] JavaGrammarParser.VoidMethodMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.methodOrFieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodOrFieldDecl([NotNull] JavaGrammarParser.MethodOrFieldDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.methodOrFieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodOrFieldDecl([NotNull] JavaGrammarParser.MethodOrFieldDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FieldRest</c>
	/// labeled alternative in <see cref="JavaGrammarParser.methodOrFieldRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldRest([NotNull] JavaGrammarParser.FieldRestContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FieldRest</c>
	/// labeled alternative in <see cref="JavaGrammarParser.methodOrFieldRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldRest([NotNull] JavaGrammarParser.FieldRestContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MethodRest</c>
	/// labeled alternative in <see cref="JavaGrammarParser.methodOrFieldRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodRest([NotNull] JavaGrammarParser.MethodRestContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MethodRest</c>
	/// labeled alternative in <see cref="JavaGrammarParser.methodOrFieldRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodRest([NotNull] JavaGrammarParser.MethodRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.fieldDeclaratorsRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDeclaratorsRest([NotNull] JavaGrammarParser.FieldDeclaratorsRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.fieldDeclaratorsRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDeclaratorsRest([NotNull] JavaGrammarParser.FieldDeclaratorsRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.methodDeclaratorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDeclaratorRest([NotNull] JavaGrammarParser.MethodDeclaratorRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.methodDeclaratorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDeclaratorRest([NotNull] JavaGrammarParser.MethodDeclaratorRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.voidMethodDeclaratorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVoidMethodDeclaratorRest([NotNull] JavaGrammarParser.VoidMethodDeclaratorRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.voidMethodDeclaratorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVoidMethodDeclaratorRest([NotNull] JavaGrammarParser.VoidMethodDeclaratorRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameters([NotNull] JavaGrammarParser.FormalParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameters([NotNull] JavaGrammarParser.FormalParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.formalParameterDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameterDecls([NotNull] JavaGrammarParser.FormalParameterDeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.formalParameterDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameterDecls([NotNull] JavaGrammarParser.FormalParameterDeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.formalParameterDeclsRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameterDeclsRest([NotNull] JavaGrammarParser.FormalParameterDeclsRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.formalParameterDeclsRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameterDeclsRest([NotNull] JavaGrammarParser.FormalParameterDeclsRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaratorId([NotNull] JavaGrammarParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaratorId([NotNull] JavaGrammarParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarator([NotNull] JavaGrammarParser.VariableDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarator([NotNull] JavaGrammarParser.VariableDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableDeclaratorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaratorRest([NotNull] JavaGrammarParser.VariableDeclaratorRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableDeclaratorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaratorRest([NotNull] JavaGrammarParser.VariableDeclaratorRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarators([NotNull] JavaGrammarParser.VariableDeclaratorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarators([NotNull] JavaGrammarParser.VariableDeclaratorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableInitializer([NotNull] JavaGrammarParser.VariableInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableInitializer([NotNull] JavaGrammarParser.VariableInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayInitializer([NotNull] JavaGrammarParser.ArrayInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayInitializer([NotNull] JavaGrammarParser.ArrayInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableInitializers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableInitializers([NotNull] JavaGrammarParser.VariableInitializersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableInitializers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableInitializers([NotNull] JavaGrammarParser.VariableInitializersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] JavaGrammarParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] JavaGrammarParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.blockStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStatements([NotNull] JavaGrammarParser.BlockStatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.blockStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStatements([NotNull] JavaGrammarParser.BlockStatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LocalVariableBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVariableBlockStatement([NotNull] JavaGrammarParser.LocalVariableBlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LocalVariableBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVariableBlockStatement([NotNull] JavaGrammarParser.LocalVariableBlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LabeledStatementBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabeledStatementBlockStatement([NotNull] JavaGrammarParser.LabeledStatementBlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LabeledStatementBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabeledStatementBlockStatement([NotNull] JavaGrammarParser.LabeledStatementBlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StatementBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementBlockStatement([NotNull] JavaGrammarParser.StatementBlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StatementBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementBlockStatement([NotNull] JavaGrammarParser.StatementBlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.localVariableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVariableDeclarationStatement([NotNull] JavaGrammarParser.LocalVariableDeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.localVariableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVariableDeclarationStatement([NotNull] JavaGrammarParser.LocalVariableDeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InnerBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInnerBlockStatement([NotNull] JavaGrammarParser.InnerBlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InnerBlockStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInnerBlockStatement([NotNull] JavaGrammarParser.InnerBlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyStatement([NotNull] JavaGrammarParser.EmptyStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyStatement([NotNull] JavaGrammarParser.EmptyStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LabeledStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabeledStatement([NotNull] JavaGrammarParser.LabeledStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LabeledStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabeledStatement([NotNull] JavaGrammarParser.LabeledStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IfStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] JavaGrammarParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] JavaGrammarParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SwitchStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatement([NotNull] JavaGrammarParser.SwitchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SwitchStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatement([NotNull] JavaGrammarParser.SwitchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>WhileStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] JavaGrammarParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>WhileStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] JavaGrammarParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DoWhileStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhileStatement([NotNull] JavaGrammarParser.DoWhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DoWhileStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhileStatement([NotNull] JavaGrammarParser.DoWhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ForStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] JavaGrammarParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] JavaGrammarParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BreakStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] JavaGrammarParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] JavaGrammarParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ContinueStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] JavaGrammarParser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ContinueStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] JavaGrammarParser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] JavaGrammarParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] JavaGrammarParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] JavaGrammarParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="JavaGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] JavaGrammarParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.statementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementExpression([NotNull] JavaGrammarParser.StatementExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.statementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementExpression([NotNull] JavaGrammarParser.StatementExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.switchBlockStatementGroups"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchBlockStatementGroups([NotNull] JavaGrammarParser.SwitchBlockStatementGroupsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.switchBlockStatementGroups"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchBlockStatementGroups([NotNull] JavaGrammarParser.SwitchBlockStatementGroupsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.switchBlockStatementGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchBlockStatementGroup([NotNull] JavaGrammarParser.SwitchBlockStatementGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.switchBlockStatementGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchBlockStatementGroup([NotNull] JavaGrammarParser.SwitchBlockStatementGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.switchLabels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchLabels([NotNull] JavaGrammarParser.SwitchLabelsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.switchLabels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchLabels([NotNull] JavaGrammarParser.SwitchLabelsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CaseExprLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseExprLabel([NotNull] JavaGrammarParser.CaseExprLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CaseExprLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseExprLabel([NotNull] JavaGrammarParser.CaseExprLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CaseEnumLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseEnumLabel([NotNull] JavaGrammarParser.CaseEnumLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CaseEnumLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseEnumLabel([NotNull] JavaGrammarParser.CaseEnumLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DefaultLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultLabel([NotNull] JavaGrammarParser.DefaultLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DefaultLabel</c>
	/// labeled alternative in <see cref="JavaGrammarParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultLabel([NotNull] JavaGrammarParser.DefaultLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.enumConstantName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumConstantName([NotNull] JavaGrammarParser.EnumConstantNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.enumConstantName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumConstantName([NotNull] JavaGrammarParser.EnumConstantNameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EnhancedForControl</c>
	/// labeled alternative in <see cref="JavaGrammarParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnhancedForControl([NotNull] JavaGrammarParser.EnhancedForControlContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EnhancedForControl</c>
	/// labeled alternative in <see cref="JavaGrammarParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnhancedForControl([NotNull] JavaGrammarParser.EnhancedForControlContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TraditionalForControl</c>
	/// labeled alternative in <see cref="JavaGrammarParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTraditionalForControl([NotNull] JavaGrammarParser.TraditionalForControlContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TraditionalForControl</c>
	/// labeled alternative in <see cref="JavaGrammarParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTraditionalForControl([NotNull] JavaGrammarParser.TraditionalForControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.forVarControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForVarControl([NotNull] JavaGrammarParser.ForVarControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.forVarControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForVarControl([NotNull] JavaGrammarParser.ForVarControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForInit([NotNull] JavaGrammarParser.ForInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForInit([NotNull] JavaGrammarParser.ForInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.forDeclarationContext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForDeclarationContext([NotNull] JavaGrammarParser.ForDeclarationContextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.forDeclarationContext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForDeclarationContext([NotNull] JavaGrammarParser.ForDeclarationContextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.forUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForUpdate([NotNull] JavaGrammarParser.ForUpdateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.forUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForUpdate([NotNull] JavaGrammarParser.ForUpdateContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimaryExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] JavaGrammarParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimaryExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] JavaGrammarParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AssignmentExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] JavaGrammarParser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignmentExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] JavaGrammarParser.AssignmentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOperator([NotNull] JavaGrammarParser.AssignmentOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOperator([NotNull] JavaGrammarParser.AssignmentOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InfixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInfixExpression([NotNull] JavaGrammarParser.InfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InfixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInfixExpression([NotNull] JavaGrammarParser.InfixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SimpleExpression2</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleExpression2([NotNull] JavaGrammarParser.SimpleExpression2Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SimpleExpression2</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleExpression2([NotNull] JavaGrammarParser.SimpleExpression2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.infixOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInfixOp([NotNull] JavaGrammarParser.InfixOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.infixOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInfixOp([NotNull] JavaGrammarParser.InfixOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrefixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixExpression([NotNull] JavaGrammarParser.PrefixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrefixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixExpression([NotNull] JavaGrammarParser.PrefixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastExpression([NotNull] JavaGrammarParser.CastExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastExpression([NotNull] JavaGrammarParser.CastExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PostfixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpression([NotNull] JavaGrammarParser.PostfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PostfixExpression</c>
	/// labeled alternative in <see cref="JavaGrammarParser.expression2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpression([NotNull] JavaGrammarParser.PostfixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.prefixOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixOp([NotNull] JavaGrammarParser.PrefixOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.prefixOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixOp([NotNull] JavaGrammarParser.PrefixOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.postfixOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixOp([NotNull] JavaGrammarParser.PostfixOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.postfixOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixOp([NotNull] JavaGrammarParser.PostfixOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralPrimary([NotNull] JavaGrammarParser.LiteralPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralPrimary([NotNull] JavaGrammarParser.LiteralPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenthesizedPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedPrimary([NotNull] JavaGrammarParser.ParenthesizedPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenthesizedPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedPrimary([NotNull] JavaGrammarParser.ParenthesizedPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IdentifierPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierPrimary([NotNull] JavaGrammarParser.IdentifierPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IdentifierPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierPrimary([NotNull] JavaGrammarParser.IdentifierPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NewCreatorPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewCreatorPrimary([NotNull] JavaGrammarParser.NewCreatorPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NewCreatorPrimary</c>
	/// labeled alternative in <see cref="JavaGrammarParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewCreatorPrimary([NotNull] JavaGrammarParser.NewCreatorPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.parExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParExpression([NotNull] JavaGrammarParser.ParExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.parExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParExpression([NotNull] JavaGrammarParser.ParExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ClassLiteralSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassLiteralSuffix([NotNull] JavaGrammarParser.ClassLiteralSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ClassLiteralSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassLiteralSuffix([NotNull] JavaGrammarParser.ClassLiteralSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccessSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAccessSuffix([NotNull] JavaGrammarParser.ArrayAccessSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccessSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAccessSuffix([NotNull] JavaGrammarParser.ArrayAccessSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArgumentsSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentsSuffix([NotNull] JavaGrammarParser.ArgumentsSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArgumentsSuffix</c>
	/// labeled alternative in <see cref="JavaGrammarParser.identifierSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentsSuffix([NotNull] JavaGrammarParser.ArgumentsSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] JavaGrammarParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] JavaGrammarParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] JavaGrammarParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] JavaGrammarParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MethodOrFieldSelector</c>
	/// labeled alternative in <see cref="JavaGrammarParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodOrFieldSelector([NotNull] JavaGrammarParser.MethodOrFieldSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MethodOrFieldSelector</c>
	/// labeled alternative in <see cref="JavaGrammarParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodOrFieldSelector([NotNull] JavaGrammarParser.MethodOrFieldSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArraySelector</c>
	/// labeled alternative in <see cref="JavaGrammarParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArraySelector([NotNull] JavaGrammarParser.ArraySelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArraySelector</c>
	/// labeled alternative in <see cref="JavaGrammarParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArraySelector([NotNull] JavaGrammarParser.ArraySelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BasicTypeType</c>
	/// labeled alternative in <see cref="JavaGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasicTypeType([NotNull] JavaGrammarParser.BasicTypeTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BasicTypeType</c>
	/// labeled alternative in <see cref="JavaGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasicTypeType([NotNull] JavaGrammarParser.BasicTypeTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ReferenceTypeType</c>
	/// labeled alternative in <see cref="JavaGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReferenceTypeType([NotNull] JavaGrammarParser.ReferenceTypeTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReferenceTypeType</c>
	/// labeled alternative in <see cref="JavaGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReferenceTypeType([NotNull] JavaGrammarParser.ReferenceTypeTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.basicType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasicType([NotNull] JavaGrammarParser.BasicTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.basicType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasicType([NotNull] JavaGrammarParser.BasicTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReferenceType([NotNull] JavaGrammarParser.ReferenceTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReferenceType([NotNull] JavaGrammarParser.ReferenceTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArguments([NotNull] JavaGrammarParser.TypeArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArguments([NotNull] JavaGrammarParser.TypeArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.referenceTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReferenceTypeList([NotNull] JavaGrammarParser.ReferenceTypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.referenceTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReferenceTypeList([NotNull] JavaGrammarParser.ReferenceTypeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifier([NotNull] JavaGrammarParser.ModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifier([NotNull] JavaGrammarParser.ModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableModifier([NotNull] JavaGrammarParser.VariableModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableModifier([NotNull] JavaGrammarParser.VariableModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.typeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArgumentsOrDiamond([NotNull] JavaGrammarParser.TypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.typeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArgumentsOrDiamond([NotNull] JavaGrammarParser.TypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.creator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreator([NotNull] JavaGrammarParser.CreatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.creator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreator([NotNull] JavaGrammarParser.CreatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.createdName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreatedName([NotNull] JavaGrammarParser.CreatedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.createdName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreatedName([NotNull] JavaGrammarParser.CreatedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.classCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassCreatorRest([NotNull] JavaGrammarParser.ClassCreatorRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.classCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassCreatorRest([NotNull] JavaGrammarParser.ClassCreatorRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaGrammarParser.arrayCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayCreatorRest([NotNull] JavaGrammarParser.ArrayCreatorRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaGrammarParser.arrayCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayCreatorRest([NotNull] JavaGrammarParser.ArrayCreatorRestContext context);
}
